apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamic-website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: website-project
  template:
    metadata:
      labels:
        app: website-project
    spec:
      containers:
      - name: website-project
        image: sathishsiddamsetty/website-project:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dynamic-website-service
spec:
  type: NodePort
  selector:
    app: website-project
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007

